In [2]:
import pandas as pd
import numpy as n
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df =  pd.read_csv("df_encoded.csv")

In [4]:
df.head()

,age,bmi,days_hospitalized,treatment_cost_inr,death_flag,gender_Male,gender_Other,disease_category_Infectious,disease_category_Mental Health,disease_category_Non-Communicable,...,hospital_type_Community Health Center,hospital_type_Government,hospital_type_Primary Health Center,hospital_type_Private,treatment_type_ICU + Ventilator,treatment_type_Medication,treatment_type_Observation,treatment_type_Palliative,treatment_type_Surgery,treatment_type_Therapy
0,70,20.1,21,102.0,0,False,False,False,False,False,...,False,True,False,False,False,True,False,False,False,False
1,27,18.3,0,1151.0,0,False,True,False,False,False,...,False,True,False,False,False,True,False,False,False,False
2,66,25.3,2,89.0,0,False,True,False,False,True,...,False,True,False,False,False,True,False,False,False,False
3,27,19.5,9,1269.0,0,False,False,True,False,False,...,False,True,False,False,False,False,False,False,True,False
4,40,29.3,31,670576.0,1,True,False,False,False,True,...,False,False,False,True,False,False,False,True,False,False

In [5]:
df.astype(int)

,age,bmi,days_hospitalized,treatment_cost_inr,death_flag,gender_Male,gender_Other,disease_category_Infectious,disease_category_Mental Health,disease_category_Non-Communicable,...,hospital_type_Community Health Center,hospital_type_Government,hospital_type_Primary Health Center,hospital_type_Private,treatment_type_ICU + Ventilator,treatment_type_Medication,treatment_type_Observation,treatment_type_Palliative,treatment_type_Surgery,treatment_type_Therapy
0,70,20,21,102,0,0,0,0,0,0,...,0,1,0,0,0,1,0,0,0,0
1,27,18,0,1151,0,0,1,0,0,0,...,0,1,0,0,0,1,0,0,0,0
2,66,25,2,89,0,0,1,0,0,1,...,0,1,0,0,0,1,0,0,0,0
3,27,19,9,1269,0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,1,0
4,40,29,31,670576,1,1,0,0,0,1,...,0,0,0,1,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,73,19,6,44863,0,0,0,0,0,0,...,0,0,0,1,0,1,0,0,0,0
19996,76,22,1,1590,0,0,0,0,0,0,...,0,0,0,1,0,1,0,0,0,0
19997,21,19,8,11361,0,1,0,0,0,0,...,0,0,1,0,0,1,0,0,0,0
19998,48,31,0,3307,0,0,0,0,0,1,...,0,0,0,1,0,0,0,0,0,0
19999,2,27,6,6667,0,1,0,0,0,0,...,0,1,0,0,0,1,0,0,0,0

In [6]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

In [7]:
X = df.drop("death_flag",axis = 1)
y = df["death_flag"]

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [9]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42)

In [10]:
model.fit(X_train,y_train)

RandomForestClassifier(max_depth=10, random_state=42)

In [11]:
y_pred = model.predict(X_test)

In [12]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [13]:
accuracy_score(y_test,y_pred)

0.93425

In [14]:
confusion_matrix(y_test,y_pred)

array([[3636,   22],
       [ 241,  101]], dtype=int64)

In [15]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.94      0.99      0.97      3658
           1       0.82      0.30      0.43       342

    accuracy                           0.93      4000
   macro avg       0.88      0.64      0.70      4000
weighted avg       0.93      0.93      0.92      4000

In [16]:
import joblib

# Train final model on full data
from sklearn.ensemble import RandomForestRegressor

model = RandomForestClassifier(
    n_estimators=100,
    max_depth=10,
    random_state=42,

)

model.fit(X, y)

# Save model
joblib.dump(model, "predictiing_death_model.pkl")

# Save columns (VERY IMPORTANT)
joblib.dump(X.columns.tolist(), "death_model_columns.pkl")

print("Model and columns saved successfully!")

Model and columns saved successfully!

Model and columns saved successfully!